# Generated by Django 3.1.6 on 2021-02-11 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercykids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 9, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 20, 40, 34, 953546)),
        ),
    ]
