version: "3.2"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    volumes:  # container:local (mount)
      - ./data/db:/data/db
    container_name: "mariadb"
